# Nome da ação: "Rodar Testes Unitários"
name: Run Unit Tests

# Quando isso vai acontecer? Sempre que algo for enviado para o repositório (push)
on: [push]

# Definindo o que a ação vai fazer
jobs: 
    run-unit-tests:  # Nome do trabalho que vai rodar
        name: Run Unit Tests  # Nome do trabalho visível
        runs-on: ubuntu-latest  # Onde o trabalho vai rodar (em um servidor com o Ubuntu mais recente)

        steps:  # Passos que o trabalho vai seguir
            # Passo 1: Baixar o código do repositório
            - uses: actions/checkout@v4

            # Passo 2: Preparar o ambiente com o Node.js versão 20
            - uses: actions/setup-node@v4
              with:
                node-version: 20  # Usar o Node.js versão 20
                cache: 'npm'  # Guardar as dependências no cache para acelerar o processo

            # Passo 3: Instalar as dependências do projeto (garante que tudo está pronto)
            - run: npm ci

            # Passo 4: Rodar os testes do projeto
            - run: npm run test  # Executa os testes unitários
